### ISSUE TITLE
Controlled operations

### ISSUE THREAD

**Issue by devildonkey1392** [iic-jku/dd_package#38]
Hi,

Can you use an example to show us how to create a controlled operation such as CNOT in README.md?

Thanks a lot!

**Comment by hillmich** [comment]
Hi,

you can create controlled operations by passing a control qubit to the `makeGateDD(operation, number of qubits, controls, target)` method.

For CNOT, it would look like this:

```cxx
auto dd = std::make_unique<dd::Package>(2);

// CNOT on Qubit 0, positively controlled by Qubit 1 (Controls are implicit positive unless made explicitly negative)
auto cx_gate = dd->makeGateDD(dd::Xmat, 2, dd::Control{1}, 0); 
```

A Toffoli can be constructed as follows:

```cxx
using namespace dd::literals; // for the _pc (positive control) user-defined literal

auto dd = std::make_unique<dd::Package>(3);
auto toffoli_gate = dd->makeGateDD(dd::Xmat, 3, {2_pc, 1_pc}, 0);
```

With less syntactic sugar, the set of controls would be `dd::Controls{dd::Control{2}, dd::Control{1}}` instead of `{2_pc, 1_pc}`.

You might want to have a look at [iic-jku/qfr](https://github.com/iic-jku/qfr), which does some wrapping around dd_package to make it easier to use, such as functions in https://github.com/iic-jku/qfr/blob/69ccc4288346982635d1c20641b4b342fe90d743/include/QuantumComputation.hpp#L261

Please don't hesitate to ask if this doesn't answer your question.

**Comment by devildonkey1392** [comment]
Hi,

I see.

Thanks for your help.
